### ISSUE TITLE
Add National News for Canada News Channel

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/File-Maker#10]
If your Wii is set to Canada right now and you access the News Channel, you will see US national news. I want to fix that and put national news from a news agency like the Canadian Press in there so the Canada News Channel will have some Canadian news.

**Comment by larsenv** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add National News for Canada News Channel](https://trello.com/c/SC4JhnI7/5-add-national-news-for-canada-news-channel)

**Comment by InternalLoss** [comment]
Dear potential Hacktoberfest users; thank you for helping us with this! You are helping Nintendo Wii owners by helping restore our services. Please see the CONTRIBUTING file in the folder for the service on specific information. Thanks!
