### ISSUE TITLE
Japanese Forecast Support

### ISSUE THREAD

**Issue by ghost** [RiiConnect24/File-Maker#3]
FORE06 occurs on Japanese Forecast Channel due to lack of finished support.

Japanese Forecast dumps (`forecast.bin` and `short.bin`) would be the best help to ensure we get it working. (we have those already)
![](https://github.trello.services/images/mini-trello-icon.png) [Japanese Support](https://trello.com/c/MaXLJz7U/1-japanese-support)

**Comment by PokeAcer549** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Japanese Support](https://trello.com/c/MaXLJz7U/1-japanese-support)

**Comment by larsenv** [comment]
It's not an unknown fix, it's that we **haven't finished support for it yet** silly. 😛

**Comment by jxgreen5** [comment]
I can help!

**Comment by CaptainGBA** [comment]
Famicom has a Wii he can help!

**Comment by jxgreen5** [comment]
I can help!

**Comment by MarkTheFreak** [comment]
Your wish has been granted

**Comment by KcrPL** [comment]
Closing issue as Japanese Forecast is now working.
