### ISSUE TITLE
Australian News Channel

### ISSUE THREAD

**Issue by MarkTheFreak** [RiiConnect24/File-Maker#32]
Currently, Reuters EU is used for Australian news. This is a problem as Reuters rarely report on Australian news. 

Steps to Reproduce :
- Take a look at Australia on the News Channel and take a look at how little news articles there is.

**Comment by KcrPL** [comment]
I'm sorry but I think we won't do anything with that.

**Comment by larsenv** [comment]
I am interested in looking at it, but I need a good news source to use (that has locations associated with the articles)

**Comment by InternalLoss** [comment]
A good source will be needed for sure (with locations) if Australian news is a goal.

**Comment by larsenv** [comment]
I was thinking of using AP for Australian news since I didn't really like the ones I found.

**Comment by MarkTheFreak** [comment]
I should also mention that when Reuters EU reported on the Margaret River shootings, the location was set to "Sydney" even though Margaret River is located in Western Australia.

**Comment by larsenv** [comment]
OK, I believe that is a common thing that happens, it has nothing to do with us.

**Comment by TheGamerWithMore-zz** [comment]
There's news.com.au which has locations. 
ABC News (abc.net.au/news) which has loads of high quality images and locations.

**Comment by larsenv** [comment]
We talked about using Associated Press. If they have the location at the start of the article that'd be good, but I swear we checked ABC News out.
