### ISSUE TITLE
Make RSA Signer smarter

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/File-Maker#34]
I think we need to rewrite RSA Signer to use pycryptodome for AES encryption, and make the argument parts better. It feels kind of hacky in its current state.

@v0idst4r do you want to work on this?

**Comment by v0idst4r** [comment]
Can you try out the news generation on the python3 branch? Not sure if I want to do this to master atm

**Comment by larsenv** [comment]
I forgot that this PR was open, but I've rewritten the whole thing back in December, so it's done now.
