### ISSUE TITLE
Article Screw-Up Bug

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/File-Maker#35]
Basically, there's an error with the News Channel where an extra offset/size is present for something I can't exactly pinpoint, and it screws up all the articles for that file. Pictures and locations are fine, however.

![Screenshot](https://cl.ly/s3NB/Screen%20Shot%202018-06-04%20at%207.46.42%20PM.png)
![Bug](https://cl.ly/s2vM/Screen%20Shot%202018-06-04%20at%207.54.01%20PM.png)

People have bothered me on Discord about it.

Hopefully @v0idst4r can help debug it.

**Comment by larsenv** [comment]
I think cd573baff6668150b16f0bc22497eae0501737d4 might fix the problem, it seems like the issue is that it's writing offsets to entries that don't exist, thus it creates them. No idea why that would be, since it uses the same method to loop through the articles.

**Comment by larsenv** [comment]
Looks like that didn't really fix it, I saw it happen again.

**Comment by ghost** [comment]
Didn't think it would.

**Comment by larsenv** [comment]
@v0idst4r You know what, I think it might have fixed it since I haven't seen the bug since I commented... If I don't see it for a couple more days I'll close the issue.

**Comment by larsenv** [comment]
The issue has happened a few times since the last comment on this issue.

f3324b284043450cf20e6490ed05261cb870f811 might fix it, the issue might have been caused with it writing captions and credits appending to the pictures table.

**Comment by larsenv** [comment]
The news has been fine after f3324b284043450cf20e6490ed05261cb870f811, so I'm gonna close this as it seems to be fixed.
