### ISSUE TITLE
Everybody Votes Channel script needs cleanup

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/File-Maker#36]
The  Everybody Votes Channel script is a mess and it's pretty hacky (but it at least gets the job done). It needs a massive cleanup. I noticed that it's still reading from a config.py file instead of config.json today...

I assigned Void and AMF to this issue if they want to help.

**Comment by AwesomeMarioFan** [comment]
I agree with you - I will help out.

**Comment by Rexogamer** [comment]
Not to be annoying, but any news? If you forgot because of other, more important things (_cough_ cmoc), fair enough.

**Comment by larsenv** [comment]
Well, AMF has been very busy with college. The script at least works, cleaning it up is just a nice thing to do.

**Comment by Rexogamer** [comment]
Very fair.

**Comment by larsenv** [comment]
I finally pushed a cleanup of the EVC script. It also now uses Python3 instead of Python2.
