### ISSUE TITLE
Everybody Votes Channel "Worldwide Results" "Awaiting Results" error.

### ISSUE THREAD

**Issue by KniteRite** [RiiConnect24/File-Maker#37]
Short Description of Issue: 
Worldwide "Awaiting Results" error.
Long Issue: 
Basically i went onto Everybody Votes Channel and went to results and i wasn't able to click on Worldwide results. it just said Awaiting Results and the answers wouldn't even show up.
Steps to Reproduce :
- Go to the "Everybody Votes Channel"
- Go to "Results"
- Look at "Worldwide Results"

**Comment by larsenv** [comment]
This is not an issue with the File-Maker. Please do not make GitHub issues about this sort of problem again.

We cannot guarantee that the EVC will work perfectly for you. There is some weird problem with the EVC where it can hang on "Awaiting Results". You'll have to wait until the next poll or a day or two.
