### ISSUE TITLE
Discord requires phone number

### ISSUE THREAD

**Issue by fakkunamae** [RiiConnect24/File-Maker#47]
Holy moly this website (git) is a chore to use. I hope someone sees this. I am getting weather00006 error for riiconnect 24, I cant report the bug on discord due to your draconian anti privacy and anti trust nintendo ninja thwarting net. I have tried installing several times. Uncertain what to do next. Only weather doesn't work.

**Comment by Artuto** [comment]
> draconian anti privacy and anti trust nintendo ninja thwarting net

What the fuck

For support send us a mail at support@riiconnect24.net

You can follow this guide https://wii.guide/riiconnect24-batteryfix
