### ISSUE TITLE
The city of Cuenca does not appear on the weather channel

### ISSUE THREAD

**Issue by jmcspain** [RiiConnect24/File-Maker#48]
## Short Description of Issue
The city of Cuenca does not appear on the weather channel

## Long Issue
The city of Cuenca does not appear on the weather channel.

Spain --> Castile-La Mancha --> Cuenca

![imagen](https://user-images.githubusercontent.com/48658161/95981516-0d02e280-0e1f-11eb-9746-7ac87129fc41.png)
See in map: https://www.qwant.com/maps/place/admin:osm:relation:344096@Cuenca

Lat: `40.1777127`
Long: `-2.2403137`

## Steps to Reproduce 
- Open "Weather channel".
- Search "Cuenca".
- Does not appear on the map.

Thanks

**Comment by larsenv** [comment]
Thanks for making the issue. I checked the code and it doesn't look like Cuenca is in the list of cities for Spain. Is it a major city?

**Comment by Peter0x44** [comment]
According to Wikipedia, it had a population of 54,898 people in 2018
Not sure it really counts as "major"

**Comment by KniteRite** [comment]
Some cities were removed from the News Channel and Forecast Channel to reduce load times.

**Comment by Peter0x44** [comment]
None were removed deliberately - although it's true there is a limit to how much you can reasonably have

It is more accurate to say "was never present"
