### ISSUE TITLE
Sun/moon weather icons showing for incorrect times

### ISSUE THREAD

**Issue by HilbertIdeals5** [RiiConnect24/File-Maker#49]
Short Description of Issue: 
The 6-hourly weather icons for the Forecast Channel show the sun and moon for the wrong times.

Long Issue: 
The short description, plus these details: the sun in the 12am-6am section, a time period when the sun is mostly _not_ up; and the moon is in 12pm-6pm section, a time period when the moon is _definitely_ not up, or at least when the sun is up and the moon isn't as visible. It's a little unintuitive when you're glancing at the forecast. Hopefully it'll be a small fix.

Here's a pic of what I mean:
![rc24-fc daynite](https://user-images.githubusercontent.com/63978875/107152423-be310980-6935-11eb-8e51-abd3fbc8e9e4.png)

Steps to Reproduce :
- Go to the Forecast Channel from the Wii Menu
- Go to the Globe, and find a city with totally clear weather for a whole day.
- Click on the Today/Tomorrow weather icon, and you'll see something like the above pic.

**Comment by larsenv** [comment]
I've noticed this as well. Thanks for reminding me about it lol. I'm not sure if it's a problem of how we're parsing the hourly Forecast or if it's what AccuWeather is returning.

Not all of the hourly Forecast used to show up until we switched the AccuWeather API we used.

**Comment by larsenv** [comment]
Fixed in e25060b58aed2a48ac090c5161436a9b46a3dab4.

![HAFE01_2021-02-13_11-29-05](https://user-images.githubusercontent.com/4673969/107856611-eebdeb00-6dee-11eb-9494-7b9442c33e55.png)
