### ISSUE TITLE
Some news articles show up twice (in slide show at least)

### ISSUE THREAD

**Issue by JPeisach** [RiiConnect24/File-Maker#54]
If you use the slide show you will see some articles can appear more than once. I had this yesterday and today it was the shooting in southern Florida.

I might PR a mechanism to check this.

**Comment by larsenv** [comment]
The thing is that it's kind of tricky to remove those duplicates.

We check the exact title of an article to detect duplicates, but sometimes the text on the headline changes so it still shows up...

**Comment by larsenv** [comment]
ok, I just implemented some code to remove similar-looking news headlines, treating them as duplicates.

I've actually wanted to fix that for years, it was just a few lines of code to fix it. Why have I never done it?
