### ISSUE TITLE
The amount of Sports news may want to be be capped

### ISSUE THREAD

**Issue by JPeisach** [RiiConnect24/File-Maker#55]
It's literally insane. You don't need to slide show to see that it's like twice as large as the international news. A cap could be used to check for this stuff.

**Comment by larsenv** [comment]
Is this really an issue though? I guess AP makes more sports news than international.

We do have a cap on how much news can be put in a file per hour because of file size limits...

**Comment by HilbertIdeals5** [comment]
To be honest, it does look really strange. In a single slideshow, I often see multiple articles w/ the exact same thumbnail and near-identical titles with only a single word changed. And I don't think this is just with sports, it's with just about every section, including the National and International News.
