### ISSUE TITLE
Error 238404 in EVC

### ISSUE THREAD

**Issue by Matejono** [RiiConnect24/File-Maker#56]
This problem started approx. month ago. Whenever I click to submit votes, it gives me this error. I searched it and it said that its HTML error "Not found". I tried to message everybody, but nobody responded. BTW, my Wii is set to Poland, if that helps.

**Comment by noahpistilli** [comment]
Try setting your Wii's region to the United Kingdom.

**Comment by larsenv** [comment]
We do support Poland. Maybe try to repatch and reinstall EVC? It's odd that it'd be 404ing.

**Comment by Matejono** [comment]
Alright, I tried to reinstall it, but now it gives me error 000000 instead of 238404 when I try to submit votes. I also looked at latest results on web, not a single vote from Poland. I dont know whats happening.

**Comment by noahpistilli** [comment]
Did you grab the EVC wad from the [RiiConnect24 Patcher](https://github.com/RiiConnect24/RiiConnect24-Patcher/releases/tag/v1.4.2.1-v1.1.2)?

**Comment by Matejono** [comment]
Sketch, Yes

**Comment by Matejono** [comment]
So, I tried it again. I repatched (official patcher like always), reinstalled, even erased my previous data. Still error 000000, when submitting votes or suggesting poll. I tried to change to UK and also Ireland, both worked. So it has to be on other side, I assume.

**Comment by Matejono** [comment]
Ok, I tried formatting it, now it shows 238404 again. Please, can you take look at it? Tested UK, Ireland + Finland and Norway, all worked, only Poland did not.

**Comment by larsenv** [comment]
Are you trying to get this working on a real Wii or Dolphin?

**Comment by Matejono** [comment]
On real wii, of course.

**Comment by Matejono** [comment]
So, I have good and bad news. Good is that suggesting polls appears to be fixed, bad is that I still cant vote, because of error 238404, maybe the submitting link is broken, I dont know.

**Comment by larsenv** [comment]
A thought just popped into my head. Are you using the RiiConnect24 DNS Server written in Python that runs on your computer? I suspect that is the issue.

Turn it off and try again. It's unnecessary.

**Comment by Matejono** [comment]
I told you that Im using it on real Wii, not Dolphin

**Comment by Matejono** [comment]
And I dont have server running on computer, so...

**Comment by Matejono** [comment]
No, I dont have it, so thats not gonna be this issue

**Comment by Matejono** [comment]
So its been pretty long time since my last reply, but today I installed EVC again, so far everything works, no 404-ing, so Im gonna close this issue as resolved, however, if it shows up again I will reopen this issue. Thank you for your support.
