### ISSUE TITLE
Progress Bar for News Channel

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/File-Maker#8]
AwesomeMarioFan has made a fancy progress bar that displays when downloading forecast data for the Forecast Channel, and I want to add that to the News Channel.

**Comment by larsenv** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Progress Bar for News Channel](https://trello.com/c/kWLujXgR/4-progress-bar-for-news-channel)

**Comment by InternalLoss** [comment]
Dear potential Hacktoberfest users; thank you for helping us with this! You are helping Nintendo Wii owners by helping restore our services. Please see the CONTRIBUTING file in the folder for the service on specific information. Thanks!

**Comment by ghost** [comment]
Progress bar for the news channel as in modifying the news channel and repacking it into a wad to have people install?

**Comment by larsenv** [comment]
It was something I was gonna add but I'm not adding it anymore.

**Comment by KcrPL** [comment]
Why not?

**Comment by larsenv** [comment]
Because of the way the script works.
